# Site settings
title: jarinosuke blog
email: naokiishikawa0808@gmail.com

url: "http://blog.jarinosuke.com"
twitter_username: jarinosuke
github_username:  jarinosuke

# Build settings
markdown: kramdown
